cadena=input("Ingrese una palabar: ")
numero=int(input("Ingrese un número: "))
decimal=float(input("Ingrese un número décimal: "))
print(cadena)
print(type(cadena))
print(numero)
print(type(numero))
print(decimal)
print(type(decimal))